### PR TITLE
docs(README): How to handle duplicate style tags

### PR DESCRIPTION
**Pull request by OlzhasAlexandrov**

### CODE REVIEW

**Comment by edarioq** [comment]
Is this still a viable solution, also this problem occurs not only with CSS but with JS tags as well. Read: **Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead.**

**Comment by o-alexandrov** [comment]
- You should be using [mini-css-extract-plugin](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/151) the same way you would extract-text-webpack-plugin.
  - You should change the configuration accordingly, but the overall meaning won't
- CSS and JS handling would be different and it depends on how you are using scripts in your project.
  - The config from the newest prerender-spa-plugin, `postProcess`, should help you to resolve your issue.

**Comment by edarioq** [comment]
For anyone who needs this, this worked for me in **vue.config.js**:

```
postProcess(renderedRoute) {
            renderedRoute.html = renderedRoute.html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/g,'');
            return renderedRoute;
          }
```

**Comment by edarioq** [comment]
The `postProcess` replaces everything that `vue`and the `prerender`plugin renders into the HTML. So I can't just use it because I strip away all script tags generated in the final HTML.

**Comment by o-alexandrov** [comment]
Please be informed that `postProcess` can do absolutely whatever you'd like.
Virtually unlimited manipulations on the result as you define what you would like to do with the produced HTML via a function.

Most common one is to use regex to find what you would like to remove and do it.

**Comment by edarioq** [comment]
Thanks @o-alexandrov but that remove all the `script`. All of them, even the ones not duplicated. Could you point me to a working example?

I have:

```
postProcess(renderedRoute) {

            renderedRoute.html = renderedRoute.html.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi,'');

            return renderedRoute;
          }
```

**Comment by o-alexandrov** [comment]
@edarioq 
You might try inserting your text into a playground for regex manipulations, for example here:
https://regexr.com/

Then, come up with a regex that would achieve what you would like.

In other words, your code is fine, you just need to write proper regex for your particular case.

**Pull request merged**
