### PR TITLE
Fixed #204

### LINKED ISSUE #204: DeprecationWarning: Tapable.plugin is deprecated
NODE_OPTIONS=--trace-warnings yarn build

```
⠋ building for production...(node:11368) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
    at PrerenderSPAPlugin.apply (node_modules/prerender-spa-plugin/es6/index.js:57:12)
    at webpack (node_modules/webpack/lib/webpack.js:37:12)
    at rm (node_modules/@triotech/vue-core/build/build.js:21:3)
    at next (node_modules/rimraf/rimraf.js:75:7)
    at CB (node_modules/rimraf/rimraf.js:111:9)
    at node_modules/rimraf/rimraf.js:137:14
    at FSReqWrap.oncomplete (fs.js:182:21)
```

### PR DESCRIPTION
**Pull request by qkdreyer**

### CODE REVIEW

**Comment by Tribex** [comment]
LGTM!

**Comment by qkdreyer** [comment]
Feel free to release a new version ASAP :)

**Comment by Tribex** [comment]
Noted. I'll get on it when I have time.

**Comment by Tribex** [comment]
@qkdreyer Done! See 8d1bae9108a6962d7a9af2600760369f1f09f24a

**Comment by qkdreyer** [comment]
Awesome @Tribex, thanks :)

**Pull request merged**
