### PR TITLE
Added documentation for catch-all pages

### PR DESCRIPTION
**Pull request by jdrydn**
As discussed in #29 here is a PR updating `README.md` with a suggestion for a catch-all page implementation 💪

### CODE REVIEW

**Comment by jdrydn** [comment]
Given the section at the top of the README about SEO I've included a short note about the impact of catch-all routes & SEO too 😉

**Comment by sammkj** [comment]
I think this will be better if it's done at server level (ie, Nginx, Apache, etc..). If you're using S3, you can also specify error fallback under bucket settings.

**Comment by jdrydn** [comment]
@sammkj That’s a valid point however if you’re hosting your project via [GitHub Pages](https://pages.github.com) or similar, where you can’t control these fine-grain settings, then this is pretty useful knowledge to have!

**Comment by sammkj** [comment]
Ahh, you're right! I didn't think of that! :sweat_smile:

**Comment by Tribex** [comment]
Hey @jdrydn, thanks for the contribution! In my opinion it would be a great starter for a blog post or article.
However, since it doesn't quite directly relate to this project, I'm going to go ahead and leave it out of the README for now.

**Pull request closed without merging**
